language: Swift
osx_image: xcode10
xcode_project: TLNetTool.xcodeproj
before_install:
- brew update
- brew install carthage
install:
- carthage update --plarform iOS
script: xcodebuild -project TLNetTool.xcodeproj -scheme "TLNetTool" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=latest'
cartfile: ./Cartfile
